/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface filesEntity {
  'expiry': number | null;
  'filename': string | null;
  'id': number;
  'message': number | null;
  'path': string;
  'room': number | null;
  'size': number;
  'uploaded': number;
  'uploader': number | null;
}
export interface first_reactorsEntity {
  '_order': any | null;
  'at': number | null;
  'reaction': number | null;
  'user': number | null;
}
export interface inboxEntity {
  'body': any;
  'expiry': number | null;
  'id': number | null;
  'posted_at': number | null;
  'recipient': number;
  'sender': number;
}
export interface message_detailsEntity {
  'data': any | null;
  'data_size': number | null;
  'edited': number | null;
  'filtered': boolean | null;
  'id': number | null;
  'posted': number | null;
  'room': number | null;
  'seqno': number | null;
  'seqno_creation': number | null;
  'seqno_data': number | null;
  'seqno_reactions': number | null;
  'session_id': string | null;
  'signature': any | null;
  'user': number | null;
  'whisper': number | null;
  'whisper_mods': boolean | null;
  'whisper_to': string | null;
}
export interface message_historyEntity {
  'data': string;
  'message': number;
  'replaced': number;
  'signature': any;
}
export interface message_metadataEntity {
  'data_size': number | null;
  'data_unpadded': any | null;
  'edited': number | null;
  'filtered': boolean | null;
  'id': number | null;
  'posted': number | null;
  'room': number | null;
  'seqno': number | null;
  'seqno_creation': number | null;
  'seqno_data': number | null;
  'seqno_reactions': number | null;
  'session_id': string | null;
  'signature_length': any | null;
  'user': number | null;
  'whisper_mods': boolean | null;
  'whisper_to': string | null;
}
export interface message_reactionsEntity {
  'at': number | null;
  'id': number | null;
  'message': number | null;
  'reaction': string | null;
  'user': number | null;
}
export interface messagesEntity {
  'data': any | null;
  'data_size': number | null;
  'edited': number | null;
  'filtered': boolean;
  'id': number;
  'posted': number;
  'room': number;
  'seqno': number;
  'seqno_creation': number;
  'seqno_data': number;
  'seqno_reactions': number;
  'signature': any | null;
  'user': number;
  'whisper': number | null;
  'whisper_mods': boolean;
}
export interface needs_blindingEntity {
  'blinded_abs': string;
  'user': number;
}
export interface pinned_messagesEntity {
  'message': number;
  'pinned_at': number;
  'pinned_by': number;
  'room': number;
}
export interface reactionsEntity {
  'id': number;
  'message': number;
  'reaction': string;
}
export interface room_moderatorsEntity {
  'admin': any | null;
  'global_moderator': any | null;
  'room': number | null;
  'room_moderator': any | null;
  'session_id': string;
  'user': number | null;
  'visible_mod': any | null;
}
export interface room_usersEntity {
  'last_active': number;
  'room': number;
  'user': number;
}
export interface roomsEntity {
  'accessible': boolean;
  'active_users': number;
  'created': number;
  'description': string | null;
  'id': number;
  'image': number | null;
  'info_updates': number;
  'message_sequence': number;
  'name': string;
  'read': boolean;
  'token': string;
  'upload': boolean;
  'write': boolean;
  'rate_limit_size': number | undefined;
  'rate_limit_interval': number | undefined;
}
export interface user_ban_futuresEntity {
  'at': number;
  'banned': boolean;
  'room': number | null;
  'user': number;
}
export interface user_permission_futuresEntity {
  'at': number;
  'read': boolean | null;
  'room': number;
  'upload': boolean | null;
  'user': number;
  'write': boolean | null;
}
export interface user_permission_overridesEntity {
  'accessible': boolean | null;
  'admin': boolean;
  'banned': boolean;
  'moderator': boolean;
  'read': boolean | null;
  'room': number;
  'upload': boolean | null;
  'user': number;
  'visible_mod': boolean;
  'write': boolean | null;
}
export interface user_permissionsEntity {
  'accessible': any | null;
  'admin': any | null;
  'banned': any | null;
  'global_moderator': boolean | null;
  'moderator': any | null;
  'read': any | null;
  'room': number | null;
  'room_moderator': any | null;
  'session_id': string | null;
  'upload': any | null;
  'user': number | null;
  'visible_mod': any | null;
  'write': any | null;
}
export interface user_reactionsEntity {
  'at': number;
  'reaction': number;
  'user': number;
}
export interface user_request_noncesEntity {
  'expiry': number;
  'nonce': any;
  'user': number;
}
export interface usersEntity {
  'admin': boolean;
  'banned': boolean;
  'created': number;
  'id': number;
  'last_active': number;
  'moderator': boolean;
  'session_id': string;
  'visible_mod': boolean;
}
